require:
  - 'rubocop-performance'
  - 'rubocop-rspec'

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Naming/FileName:
  Exclude:
    - 'lib/redis-interlock.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
